
# USE NODE v20 that uses alphine    
FROM node:20-alpine

# Create a 'app' DIR (Standard)
WORKDIR /app

# First (.) - Copy lahat ng files sa local
# Second (.) - Lagay lahat sa app
COPY . .

# Run the hello.js
CMD node hello.js